### ISSUE TITLE
android

### ISSUE THREAD

**Issue by twiuglufosfa** [monero-ecosystem/qml-xmr#2]
can this be installed on android emulator?

im starting new project for android gui that need a lot of changes in qml.

**Comment by sanderfoobar** [comment]
Hey @twiuglufosfa 

What I would do, is run this program with `isMobile: true` and `isAndroid: true` in `appWindow` (`monero-gui.qml`).

**Comment by sanderfoobar** [comment]
If you are starting completely from scratch, I would recommend that you use https://github.com/penk/qml-livereload instead.

**Comment by twiuglufosfa** [comment]
hello,

i dont want to start from scratch so im trying to run qml files(with small changes like isandroid)

 and is not possible with this program.

i thought that was

**Comment by sanderfoobar** [comment]
qml-xmr is meant as a **seperate** environment so one can **focus on design and QML** code. Upon finished, one can migrate the code and create a real PR for repository monero-gui.
